branch-defaults:
  main:
    environment: animus-env
    group_suffix: null
global:
  application_name: animus
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
